services:
  app:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=pg_serverauthentication
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '380MB'
